### Store Transacion
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
  "fromAccountId": "5riz_l9tTcAeh0YaWuUJV",
  "toAccountId": "RCwzLj8nApjWVBTvmFhFO",
  "amount": 50
}

### Show Transaction
GET http://localhost:3000/api/transactions/1
