### Store a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "fullName": "Nome Completo",
  "bi": "000000000LA001",
  "email": "email@example.com",
  "password": "Password@1234",
  "account": {
    "accountTypeId": 2,
    "initialBalance": 100.50
  }
}

### Show a User
GET http://localhost:3000/api/users/K4pqDozNWHa4Wa5XSbl2G

### Store Account to User
POST http://localhost:3000/api/users/zMsapWIs9lSZciv3Txff7/accounts
Content-Type: application/json

{
  "type": "COMMON",
  "initialBalance": 100
}