### Store a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "fullName": "Nome",
  "BI": "000000000LA001",
  "email": "email@example.com",
  "password": "StrongPassword-1234",
  "userTypeId": 1
}