### Store a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "fullName": "Nome Completo",
  "bi": "000000000LA001",
  "email": "email@example.com",
  "password": "Password@1234",
  "account": {
    "accountTypeId": 2,
    "initialBalance": 100.50
  }
}